In [1]:
import numpy as np
print(np.__version__)

1.26.0


In [2]:
arr1 = np.full(shape=(3,3),fill_value=55)
print(arr1)

[[55 55 55]
 [55 55 55]
 [55 55 55]]


In [3]:
arr2 = np.zeros(10)
arr2[4] = 1
print(arr2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [4]:
arr3 = np.arange(0, 10, 1)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
arr4 = np.arange(9)
arr4 = arr4.reshape(3,3)
print(arr4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
data = np.array([1, 2, 3])

print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

2
[1 2]
[2 3]
[2 3]


In [7]:
arr5 = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr5[-3:-1])

[5 6]


In [8]:
arr6 = np.array([[1, 2, 3,4,5], [6, 7, 8, 9, 10]])
print(arr6[0:2, 2])
print(arr6[0:1, 2])
print(arr6[1:2, 2])

[3 8]
[3]
[8]


In [9]:
arr7 = np.array([1, 2, 3])
arr8 = np.array([4, 5, 6])
arr = np.stack((arr7, arr8), axis=0)
print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
array = np.array([28, 13, 45, 12, 4, 8, 0])
print(array)
print(np.argsort(array))

[28 13 45 12  4  8  0]
[6 4 5 3 1 0 2]


In [22]:
arr = np.zeros((5, 5))
# for x in arr:
#     arr[x] = np.arange(0, 5, 1)
arr[0] = np.arange(0, 5, 1)
arr[1] = np.arange(0, 5, 1)
arr[2] = np.arange(0, 5, 1)
arr[3] = np.arange(0, 5, 1)
arr[4] = np.arange(0, 5, 1)
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
array = np.array([
    [3, 2, 8],
    [4, 12, 34],
    [23, 12, 67]
])

newRow = np.array([2, 1, 8])